### ISSUE TITLE
unimplemented color codes

### ISSUE THREAD

**Issue by Ranfir** [prophecymud/go-prophecy-issues#131]
color list includes some color codes that are not currently implemented in GoProph (such as `9). This is causing colors to render incorrectly in various places such as Kahsha's room descriptions.

![image](https://user-images.githubusercontent.com/58370848/73130673-0d2a2c00-3fcb-11ea-8001-efe68b01a28f.png)

**Comment by Ranfir** [comment]
Another example is:
![image](https://user-images.githubusercontent.com/58370848/73130651-97be5b80-3fca-11ea-9a4d-8273409d14d2.png)

**Comment by anhegofcherek** [comment]
Boo undefined behaviour :(

Turns out in CProph, if you used an undefined colour code, it acted just like the reset/terminator code.

When porting to GoProph, I made the parser just ignore it. Didn't realise how many strings we had that relied on the original behaviour.

This will be "fixed" (returned to original behaviour) in the next deploy, thanks
