### ISSUE TITLE
"Open e" references inv container item beginning with "e" instead of the east door.

### ISSUE THREAD

**Issue by Vordai-of-Prophecy** [prophecymud/go-prophecy-issues#147]
Notes:

Player typed "open e" in a room with a closed door to the east.
Player received "It's already open" message.

Player was carrying this bag in inv:
Object 'bag newbie eq -=Zubrette=-' is type container.

When I took the bag from the player and left the room, the player typed "Open e" and it correctly referred to the east door ("It's closed.")

**Comment by anhegofcherek** [comment]
This is behaviour that, I believe, dates back to ROM itself - it's certainly not a GoProph bug

If you're saying the behaviour should be different, what should the behaviour be? Should directions be checked before objects? Should directions be special cased? Both of those just feel like they shift the problem around, and lead to someone filing a "bug" about being unable to interact with an item in certain rooms.

One thing I'd like to see, in a similar vein to the recent changes I made to `wear`, is more helpful "error messages" - and I think they'll help here:

If, when they tried to `open` that bag, they were told `The Zubrette bag is already open` (rather than the unhelpful "It"), at least then it'd be clear that they hadn't done what they intended...

**Comment by Vordai-of-Prophecy** [comment]
Making the error messages clearer works for me! No need to change the default behavior.

**Comment by anhegofcherek** [comment]
The "error" messages should now be much clearer - thanks for the prompt!
