### ISSUE TITLE
auction identify

### ISSUE THREAD

**Issue by Ranfir** [prophecymud/go-prophecy-issues#165]
Seems like it shouldn't include the `You identify` part.
```
auc
No bids on this item have been received.

You identify (Tight) Allan's pants (originally [Antiquated] Iron Greaves):

Object 'allan tight pants -astring-' is type armor.
Extra flags: none.
Weight is 0, value is 0, wear level is 1.
Wear location is legs.
Armor class is 5 pierce, 5 bash, 5 slash, and 5 vs. magic.
Affects wisdom by 2.
Affects damage roll by 2.
Affects hit roll by 2.
```

**Comment by anhegofcherek** [comment]
Hm. I see where you're coming from but not clear what it could/should be instead!

**Comment by anhegofcherek** [comment]
I think I'm ok with this - I appreciate that strictly speaking you aren't "identifying" but I don't think it's too jarring and I don't see obvious improvements here

Happy to reopen this and change it if you have concrete suggestions for improvement (and thank you for raising it!) but otherwise I'm going to close this as I don't consider it a problem-to-be-fixed - I hope that seems clear and reasonable
