### ISSUE TITLE
Character creation: "No help on that word."

### ISSUE THREAD

**Issue by Ranfir** [prophecymud/go-prophecy-issues#76]
**No help on that word.** shows up on any input during character customization.

```
Creation points: 0
Experience per level: 1000
You already have the following skills:

Level  1: dagger             n/a      scrolls            n/a
          staves             n/a      wands              n/a
          recall             n/a
No help on that word.


Choices are: list,learned,premise,add,drop,info,help, and done.
No help on that word.
add priest default


priest default group added
No help on that word.

Choices are: list,learned,premise,add,drop,info,help, and done.
No help on that word.
```

**Comment by anhegofcherek** [comment]
This is similar to #19 

It turns out that help lookups use some edge-cases of the name-check code (which takes "guard" from "kill guard" and checks to see if it matches "gate guard legionnaire") that I didn't port

I _suspect_ that helps are the only place this happens, and I'm highly tempted to just fix the data...

**Comment by anhegofcherek** [comment]
I didn't fix the data, but I did fix the issue for now...

Hopefully I can clean this all up a bit with pwhelp
