### ISSUE TITLE
attacking with arrow equipped

### ISSUE THREAD

**Issue by Ranfir** [prophecymud/go-prophecy-issues#84]
Attacking with arrow equipped results in a message from the victim, but no further actions. On the CProph side, no message is given.
```
k lou
A lounging fisherman yells 'Help!  I am being attacked by Ranfir!'
```

**Comment by anhegofcherek** [comment]
I'm not convinced this is a bug - I think what you're seeing is the behaviour for `murder`, and you have `k` aliased to `murder` on Ranfir - does that sound about right?

**Comment by Ranfir** [comment]
You're absolutely correct. Apart from the message, is there any other difference in behavior between kill and murder?

**Comment by anhegofcherek** [comment]
I think, back in early ROM when there weren't PK flags and anyone could _in theory_ PK (or something like that - hence the `KILLER` flag) then the main difference was that you could `murder` players but `kill` worked only on mobs.

I'm really glad you asked this though because there are three differences:

1. The yell, as you spotted
2. The fact they're nearly identical but have slightly subtly different checks and ordering thereof that is likely to cause a bug / woe in future and means I should probably coalesce them into one
3. The fact that `kill` causes 1.5x the wait that `murder` does (!)

**Comment by anhegofcherek** [comment]
Filed as a general Prophecy issue in https://github.com/prophecymud/prophecy-issues/issues/10

**Comment by anhegofcherek** [comment]
Thanks!
